
(* definitions *)
let iand (x : int option ref) (y : int option ref) (z : int option ref) =
  match (!x,!y) with
  |  (None , _) -> ()
  |  (_ , None) -> ()    
  |  (Some 1, Some 1) -> z := Some 1    
  |  _ -> z := Some 0

let ior (x : int option ref) (y : int option ref) (z : int option ref) =
  match (!x,!y) with
  |  (None , _) -> ()
  |  (_ , None) -> ()    
  |  (Some 1, _) -> z := Some 1
  |  (_, Some 1) -> z := Some 1                      
  |  _ -> z := Some 0


let ixor (x : int option ref) (y : int option ref) (z : int option ref) =
  match (!x,!y) with
  |  (None , _) -> ()
  |  (_ , None) -> ()    
  |  (Some 1, Some 0) -> z := Some 1
  |  (Some 0, Some 1) -> z := Some 1                  
  |  _ -> z := Some 0

exception Bin2decException
  
let rec bin2dec xs n s =
  match xs with
  | [] -> n
  | (y :: t) -> (match !y with
      | Some x -> bin2dec t (n + (x * s)) (s * 2)
      | _ -> raise Bin2decException )
   

(* z : (z00 z01 z02 z03 z04 z05 z06 z07 z08 z09 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 z26 z27 z28 z29 z30 z31 z32 z33 z34 z35 z36 z37 z38 z39 z40 z41 z42 z43 z44 z45) *)

(* declarations *)
let bbk : int option ref = ref None;;
let bcc : int option ref = ref None;;
let bfb : int option ref = ref None;;
let bhw : int option ref = ref None;;
let bjf : int option ref = ref None;;
let bkq : int option ref = ref None;;
let bmp : int option ref = ref None;;
let bqr : int option ref = ref None;;
let bsb : int option ref = ref None;;
let bsn : int option ref = ref None;;
let ccq : int option ref = ref None;;
let cdk : int option ref = ref None;;
let chk : int option ref = ref None;;
let cks : int option ref = ref None;;
let cqp : int option ref = ref None;;
let crb : int option ref = ref None;;
let crj : int option ref = ref None;;
let dbc : int option ref = ref None;;
let dbv : int option ref = ref None;;
let dgj : int option ref = ref None;;
let dkh : int option ref = ref None;;
let dqm : int option ref = ref None;;
let drd : int option ref = ref None;;
let dtb : int option ref = ref None;;
let dtj : int option ref = ref None;;
let fgc : int option ref = ref None;;
let fgq : int option ref = ref None;;
let fgv : int option ref = ref None;;
let fhw : int option ref = ref None;;
let fjh : int option ref = ref None;;
let fnh : int option ref = ref None;;
let fpd : int option ref = ref None;;
let fpm : int option ref = ref None;;
let fqr : int option ref = ref None;;
let frh : int option ref = ref None;;
let frn : int option ref = ref None;;
let frs : int option ref = ref None;;
let ftb : int option ref = ref None;;
let gcf : int option ref = ref None;;
let gdk : int option ref = ref None;;
let gdw : int option ref = ref None;;
let ghf : int option ref = ref None;;
let gkc : int option ref = ref None;;
let gmf : int option ref = ref None;;
let gmq : int option ref = ref None;;
let gnp : int option ref = ref None;;
let gqj : int option ref = ref None;;
let grg : int option ref = ref None;;
let grv : int option ref = ref None;;
let gsr : int option ref = ref None;;
let gwm : int option ref = ref None;;
let hbf : int option ref = ref None;;
let hfb : int option ref = ref None;;
let hfj : int option ref = ref None;;
let hhn : int option ref = ref None;;
let hkf : int option ref = ref None;;
let htm : int option ref = ref None;;
let htp : int option ref = ref None;;
let hvs : int option ref = ref None;;
let jcf : int option ref = ref None;;
let jgg : int option ref = ref None;;
let jgv : int option ref = ref None;;
let jhf : int option ref = ref None;;
let jhv : int option ref = ref None;;
let jjp : int option ref = ref None;;
let jpk : int option ref = ref None;;
let jsr : int option ref = ref None;;
let jwb : int option ref = ref None;;
let jwv : int option ref = ref None;;
let kbj : int option ref = ref None;;
let kcf : int option ref = ref None;;
let kdv : int option ref = ref None;;
let kgr : int option ref = ref None;;
let kgw : int option ref = ref None;;
let kkh : int option ref = ref None;;
let kkq : int option ref = ref None;;
let kmg : int option ref = ref None;;
let kmj : int option ref = ref None;;
let knb : int option ref = ref None;;
let knf : int option ref = ref None;;
let krp : int option ref = ref None;;
let kth : int option ref = ref None;;
let kvc : int option ref = ref None;;
let kvt : int option ref = ref None;;
let mdn : int option ref = ref None;;
let mgg : int option ref = ref None;;
let mjj : int option ref = ref None;;
let mmr : int option ref = ref None;;
let mph : int option ref = ref None;;
let mpv : int option ref = ref None;;
let mrt : int option ref = ref None;;
let msw : int option ref = ref None;;
let mtk : int option ref = ref None;;
let mvk : int option ref = ref None;;
let mwj : int option ref = ref None;;
let ndn : int option ref = ref None;;
let nrr : int option ref = ref None;;
let nrs : int option ref = ref None;;
let nvq : int option ref = ref None;;
let pjp : int option ref = ref None;;
let pkh : int option ref = ref None;;
let pmn : int option ref = ref None;;
let pmq : int option ref = ref None;;
let pnj : int option ref = ref None;;
let prt : int option ref = ref None;;
let ptq : int option ref = ref None;;
let pvh : int option ref = ref None;;
let qbq : int option ref = ref None;;
let qdc : int option ref = ref None;;
let qhk : int option ref = ref None;;
let qjq : int option ref = ref None;;
let qkq : int option ref = ref None;;
let qmr : int option ref = ref None;;
let qns : int option ref = ref None;;
let qqp : int option ref = ref None;;
let qqs : int option ref = ref None;;
let rcf : int option ref = ref None;;
let rfq : int option ref = ref None;;
let rhr : int option ref = ref None;;
let rjm : int option ref = ref None;;
let rjq : int option ref = ref None;;
let rks : int option ref = ref None;;
let rsk : int option ref = ref None;;
let rss : int option ref = ref None;;
let rtk : int option ref = ref None;;
let rvf : int option ref = ref None;;
let rwf : int option ref = ref None;;
let rwh : int option ref = ref None;;
let shm : int option ref = ref None;;
let sjf : int option ref = ref None;;
let skj : int option ref = ref None;;
let skn : int option ref = ref None;;
let smg : int option ref = ref None;;
let snr : int option ref = ref None;;
let sqg : int option ref = ref None;;
let srn : int option ref = ref None;;
let srp : int option ref = ref None;;
let sst : int option ref = ref None;;
let stg : int option ref = ref None;;
let swn : int option ref = ref None;;
let tff : int option ref = ref None;;
let tfs : int option ref = ref None;;
let tfv : int option ref = ref None;;
let tkc : int option ref = ref None;;
let tmd : int option ref = ref None;;
let tqf : int option ref = ref None;;
let tqm : int option ref = ref None;;
let trv : int option ref = ref None;;
let tsf : int option ref = ref None;;
let tsn : int option ref = ref None;;
let twb : int option ref = ref None;;
let twp : int option ref = ref None;;
let twt : int option ref = ref None;;
let vbp : int option ref = ref None;;
let vds : int option ref = ref None;;
let vfb : int option ref = ref None;;
let vgs : int option ref = ref None;;
let vhs : int option ref = ref None;;
let vjg : int option ref = ref None;;
let vkk : int option ref = ref None;;
let vmw : int option ref = ref None;;
let vrj : int option ref = ref None;;
let vrq : int option ref = ref None;;
let vtj : int option ref = ref None;;
let vvt : int option ref = ref None;;
let wkb : int option ref = ref None;;
let wkh : int option ref = ref None;;
let wkq : int option ref = ref None;;
let wms : int option ref = ref None;;
let wnf : int option ref = ref None;;
let wqr : int option ref = ref None;;
let wtd : int option ref = ref None;;
let wtt : int option ref = ref None;;
let wtv : int option ref = ref None;;
let wwn : int option ref = ref None;;
let wwt : int option ref = ref None;;
let x00 : int option ref = ref None;;
let x01 : int option ref = ref None;;
let x02 : int option ref = ref None;;
let x03 : int option ref = ref None;;
let x04 : int option ref = ref None;;
let x05 : int option ref = ref None;;
let x06 : int option ref = ref None;;
let x07 : int option ref = ref None;;
let x08 : int option ref = ref None;;
let x09 : int option ref = ref None;;
let x10 : int option ref = ref None;;
let x11 : int option ref = ref None;;
let x12 : int option ref = ref None;;
let x13 : int option ref = ref None;;
let x14 : int option ref = ref None;;
let x15 : int option ref = ref None;;
let x16 : int option ref = ref None;;
let x17 : int option ref = ref None;;
let x18 : int option ref = ref None;;
let x19 : int option ref = ref None;;
let x20 : int option ref = ref None;;
let x21 : int option ref = ref None;;
let x22 : int option ref = ref None;;
let x23 : int option ref = ref None;;
let x24 : int option ref = ref None;;
let x25 : int option ref = ref None;;
let x26 : int option ref = ref None;;
let x27 : int option ref = ref None;;
let x28 : int option ref = ref None;;
let x29 : int option ref = ref None;;
let x30 : int option ref = ref None;;
let x31 : int option ref = ref None;;
let x32 : int option ref = ref None;;
let x33 : int option ref = ref None;;
let x34 : int option ref = ref None;;
let x35 : int option ref = ref None;;
let x36 : int option ref = ref None;;
let x37 : int option ref = ref None;;
let x38 : int option ref = ref None;;
let x39 : int option ref = ref None;;
let x40 : int option ref = ref None;;
let x41 : int option ref = ref None;;
let x42 : int option ref = ref None;;
let x43 : int option ref = ref None;;
let x44 : int option ref = ref None;;
let y00 : int option ref = ref None;;
let y01 : int option ref = ref None;;
let y02 : int option ref = ref None;;
let y03 : int option ref = ref None;;
let y04 : int option ref = ref None;;
let y05 : int option ref = ref None;;
let y06 : int option ref = ref None;;
let y07 : int option ref = ref None;;
let y08 : int option ref = ref None;;
let y09 : int option ref = ref None;;
let y10 : int option ref = ref None;;
let y11 : int option ref = ref None;;
let y12 : int option ref = ref None;;
let y13 : int option ref = ref None;;
let y14 : int option ref = ref None;;
let y15 : int option ref = ref None;;
let y16 : int option ref = ref None;;
let y17 : int option ref = ref None;;
let y18 : int option ref = ref None;;
let y19 : int option ref = ref None;;
let y20 : int option ref = ref None;;
let y21 : int option ref = ref None;;
let y22 : int option ref = ref None;;
let y23 : int option ref = ref None;;
let y24 : int option ref = ref None;;
let y25 : int option ref = ref None;;
let y26 : int option ref = ref None;;
let y27 : int option ref = ref None;;
let y28 : int option ref = ref None;;
let y29 : int option ref = ref None;;
let y30 : int option ref = ref None;;
let y31 : int option ref = ref None;;
let y32 : int option ref = ref None;;
let y33 : int option ref = ref None;;
let y34 : int option ref = ref None;;
let y35 : int option ref = ref None;;
let y36 : int option ref = ref None;;
let y37 : int option ref = ref None;;
let y38 : int option ref = ref None;;
let y39 : int option ref = ref None;;
let y40 : int option ref = ref None;;
let y41 : int option ref = ref None;;
let y42 : int option ref = ref None;;
let y43 : int option ref = ref None;;
let y44 : int option ref = ref None;;
let z00 : int option ref = ref None;;
let z01 : int option ref = ref None;;
let z02 : int option ref = ref None;;
let z03 : int option ref = ref None;;
let z04 : int option ref = ref None;;
let z05 : int option ref = ref None;;
let z06 : int option ref = ref None;;
let z07 : int option ref = ref None;;
let z08 : int option ref = ref None;;
let z09 : int option ref = ref None;;
let z10 : int option ref = ref None;;
let z11 : int option ref = ref None;;
let z12 : int option ref = ref None;;
let z13 : int option ref = ref None;;
let z14 : int option ref = ref None;;
let z15 : int option ref = ref None;;
let z16 : int option ref = ref None;;
let z17 : int option ref = ref None;;
let z18 : int option ref = ref None;;
let z19 : int option ref = ref None;;
let z20 : int option ref = ref None;;
let z21 : int option ref = ref None;;
let z22 : int option ref = ref None;;
let z23 : int option ref = ref None;;
let z24 : int option ref = ref None;;
let z25 : int option ref = ref None;;
let z26 : int option ref = ref None;;
let z27 : int option ref = ref None;;
let z28 : int option ref = ref None;;
let z29 : int option ref = ref None;;
let z30 : int option ref = ref None;;
let z31 : int option ref = ref None;;
let z32 : int option ref = ref None;;
let z33 : int option ref = ref None;;
let z34 : int option ref = ref None;;
let z35 : int option ref = ref None;;
let z36 : int option ref = ref None;;
let z37 : int option ref = ref None;;
let z38 : int option ref = ref None;;
let z39 : int option ref = ref None;;
let z40 : int option ref = ref None;;
let z41 : int option ref = ref None;;
let z42 : int option ref = ref None;;
let z43 : int option ref = ref None;;
let z44 : int option ref = ref None;;
let z45 : int option ref = ref None;;


(* assignments  *)
x00 := Some 1;;
x01 := Some 1;;
x02 := Some 0;;
x03 := Some 0;;
x04 := Some 0;;
x05 := Some 1;;
x06 := Some 0;;
x07 := Some 1;;
x08 := Some 1;;
x09 := Some 0;;
x10 := Some 1;;
x11 := Some 0;;
x12 := Some 0;;
x13 := Some 0;;
x14 := Some 1;;
x15 := Some 0;;
x16 := Some 1;;
x17 := Some 1;;
x18 := Some 0;;
x19 := Some 1;;
x20 := Some 0;;
x21 := Some 0;;
x22 := Some 1;;
x23 := Some 1;;
x24 := Some 1;;
x25 := Some 1;;
x26 := Some 0;;
x27 := Some 1;;
x28 := Some 1;;
x29 := Some 0;;
x30 := Some 1;;
x31 := Some 0;;
x32 := Some 0;;
x33 := Some 1;;
x34 := Some 1;;
x35 := Some 0;;
x36 := Some 1;;
x37 := Some 1;;
x38 := Some 1;;
x39 := Some 1;;
x40 := Some 1;;
x41 := Some 1;;
x42 := Some 1;;
x43 := Some 1;;
x44 := Some 1;;
y00 := Some 1;;
y01 := Some 0;;
y02 := Some 1;;
y03 := Some 1;;
y04 := Some 0;;
y05 := Some 0;;
y06 := Some 1;;
y07 := Some 1;;
y08 := Some 0;;
y09 := Some 1;;
y10 := Some 1;;
y11 := Some 1;;
y12 := Some 1;;
y13 := Some 0;;
y14 := Some 1;;
y15 := Some 1;;
y16 := Some 1;;
y17 := Some 0;;
y18 := Some 1;;
y19 := Some 0;;
y20 := Some 0;;
y21 := Some 1;;
y22 := Some 0;;
y23 := Some 1;;
y24 := Some 0;;
y25 := Some 1;;
y26 := Some 0;;
y27 := Some 1;;
y28 := Some 0;;
y29 := Some 0;;
y30 := Some 1;;
y31 := Some 1;;
y32 := Some 0;;
y33 := Some 1;;
y34 := Some 0;;
y35 := Some 0;;
y36 := Some 1;;
y37 := Some 0;;
y38 := Some 1;;
y39 := Some 0;;
y40 := Some 0;;
y41 := Some 0;;
y42 := Some 1;;
y43 := Some 0;;
y44 := Some 1;;

(* operations  *)
let rec foo () = 
let zs = [z00;z01;z02;z03;z04;z05;z06;z07;z08;z09;z10;z11;z12;z13;z14;z15;z16;z17;z18;z19;z20;z21;z22;z23;z24;z25;z26;z27;z28;z29;z30;z31;z32;z33;z34;z35;z36;z37;z38;z39;z40;z41;z42;z43;z44;z45] in 
let undet = List.filter (fun x -> match (!x) with | Some _ -> false | _ -> true) zs in 
if undet = [] then zs 
else ( iand   y08   x08   pkh ;
 iand   grg   twt   bbk ;
 ior   vvt   wwt   vgs ;
 ixor   x10   y10   pmq ;
 ixor   pmq   hkf   z10 ;
 ior   vmw   bfb   hkf ;
 ior   twp   qbq   kmj ;
 iand   qns   mwj   qhk ;
 ixor   dqm   cqp   z02 ;
 iand   snr   crb   htp ;
 ixor   jwv   dgj   z09 ;
 ior   sjf   rwf   wkq ;
 ixor   y02   x02   dqm ;
 iand   msw   qqp   rss ;
 ixor   fgv   bhw   z26 ;
 iand   y03   x03   ftb ;
 ixor   kmj   fnh   z24 ;
 ixor   jhv   bkq   wtt ;
 ixor   x27   y27   knf ;
 ixor   y40   x40   jhf ;
 ior   gmq   nrs   kkq ;
 ixor   y03   x03   ndn ;
 ixor   x25   y25   hfj ;
 iand   x33   y33   rvf ;
 iand   wkh   pmn   vrq ;
 ior   mgg   hbf   fhw ;
 ior   nrr   rtk   wqr ;
 iand   x00   y00   mtk ;
 ixor   crb   snr   z30 ;
 ixor   y37   x37   qns ;
 ior   kgw   wms   snr ;
 ixor   y09   x09   jwv ;
 iand   mtk   kvc   jjp ;
 ixor   x01   y01   kvc ;
 iand   jgg   bsn   fpm ;
 ior   kvt   ftb   drd ;
 iand   x15   y15   tfs ;
 ixor   x34   y34   jgv ;
 ixor   y44   x44   vjg ;
 ixor   x21   y21   fqr ;
 ixor   x36   y36   rwh ;
 iand   y30   x30   kgr ;
 ior   sqg   hfb   rfq ;
 ixor   x05   y05   kbj ;
 ior   rjq   skn   jhv ;
 iand   y17   x17   bmp ;
 iand   x28   y28   jwb ;
 iand   x44   y44   vrj ;
 ixor   wwn   gwm   z23 ;
 iand   y39   x39   gsr ;
 ixor   wkq   tfv   z15 ;
 iand   x31   y31   sst ;
 ixor   x08   y08   twt ;
 iand   wnf   rsk   pjp ;
 iand   mmr   qdc   rwf ;
 ixor   y22   x22   jsr ;
 ior   pnj   bcc   hhn ;
 ior   fpm   wtv   kth ;
 ixor   kkq   jsr   z22 ;
 ixor   srn   kth   z33 ;
 ior   vrq   mrt   tkc ;
 iand   wwn   gwm   qbq ;
 ixor   jhf   mdn   z40 ;
 ixor   y13   x13   tqf ;
 ixor   kvc   mtk   z01 ;
 ixor   stg   kdv   z35 ;
 ixor   grg   twt   z08 ;
 iand   kkq   jsr   fjh ;
 iand   tmd   shm   rjm ;
 iand   nvq   chk   gnp ;
 ior   twb   ptq   qqp ;
 ixor   x32   y32   bsn ;
 ixor   y39   x39   bkq ;
 ior   mph   vbp   stg ;
 iand   x02   y02   rks ;
 iand   dtj   hfj   frh ;
 ixor   y43   x43   qmr ;
 ixor   chk   nvq   z28 ;
 iand   x16   y16   wnf ;
 ixor   y06   x06   ghf ;
 ior   rhr   ccq   qjq ;
 iand   x38   y38   rjq ;
 iand   tsf   dtb   twb ;
 ixor   x15   y15   tfv ;
 iand   vds   gdk   skn ;
 ixor   hhn   rwh   z36 ;
 iand   x40   y40   bjf ;
 ior   wtd   cks   nvq ;
 ior   jpk   qhk   vds ;
 ixor   x14   y14   qdc ;
 iand   y19   x19   ptq ;
 iand   fnh   kmj   gqj ;
 ior   pjp   vtj   smg ;
 ixor   x11   y11   tmd ;
 ior   bbk   pkh   dgj ;
 iand   bkq   jhv   z39 ;
 iand   y07   x07   krp ;
 iand   hkf   pmq   crj ;
 iand   y22   x22   cdk ;
 ior   knb   vkk   mmr ;
 ixor   vds   gdk   z38 ;
 iand   jhf   mdn   qkq ;
 ior   vrj   gkc   z45 ;
 iand   x41   y41   mrt ;
 ixor   jgv   dkh   z34 ;
 ixor   y16   x16   vtj ;
 ior   rcf   gqj   dtj ;
 ior   rvf   bqr   dkh ;
 iand   x25   y25   swn ;
 ixor   dbv   vhs   z31 ;
 ixor   y12   x12   fgq ;
 iand   y20   x20   kcf ;
 ior   rss   kcf   mjj ;
 ixor   hfj   dtj   z25 ;
 iand   x14   y14   sjf ;
 ixor   fpd   smg   z17 ;
 iand   x21   y21   z21 ;
 iand   x43   y43   prt ;
 ixor   x31   y31   vhs ;
 ior   grv   tfs   rsk ;
 ixor   y33   x33   srn ;
 ixor   msw   qqp   z20 ;
 ior   gsr   wtt   mdn ;
 ixor   x30   y30   crb ;
 iand   y24   x24   rcf ;
 ior   frh   swn   bhw ;
 iand   htm   ndn   kvt ;
 iand   x06   y06   hbf ;
 ixor   x35   y35   kdv ;
 iand   srn   kth   bqr ;
 iand   dgj   jwv   bfb ;
 ixor   bsn   jgg   z32 ;
 ior   rjm   skj   tff ;
 iand   gcf   fhw   mpv ;
 ior   vfb   jjp   cqp ;
 ixor   x00   y00   z00 ;
 ior   crj   fgc   shm ;
 ixor   tff   fgq   z12 ;
 ixor   mwj   qns   z37 ;
 iand   vjg   kmg   gkc ;
 ixor   x19   y19   dtb ;
 ixor   hvs   tsn   z18 ;
 ixor   dtb   tsf   z19 ;
 iand   y05   x05   srp ;
 iand   kkh   bsb   kgw ;
 ior   rks   trv   htm ;
 iand   frn   ghf   mgg ;
 ixor   qjq   kbj   frn ;
 ixor   knf   vgs   z27 ;
 iand   y09   x09   vmw ;
 iand   x36   y36   dbc ;
 iand   knf   vgs   wtd ;
 ixor   y23   x23   wwn ;
 ixor   wnf   rsk   z16 ;
 ixor   y29   x29   kkh ;
 ixor   vjg   kmg   z44 ;
 ior   htp   kgr   dbv ;
 ixor   htm   ndn   z03 ;
 ixor   rfq   tqf   z13 ;
 iand   mjj   fqr   nrs ;
 ixor   gcf   fhw   z07 ;
 iand   qmr   wqr   frs ;
 iand   x32   y32   wtv ;
 ixor   x07   y07   gcf ;
 ior   gmf   pvh   tsf ;
 ixor   mjj   fqr   gmq ;
 ior   qqs   dbc   mwj ;
 ior   krp   mpv   grg ;
 iand   x34   y34   vbp ;
 iand   tff   fgq   hfb ;
 iand   drd   wkb   rhr ;
 iand   tqf   rfq   vkk ;
 iand   x13   y13   knb ;
 iand   bhw   fgv   vvt ;
 iand   hhn   rwh   qqs ;
 iand   kbj   qjq   jcf ;
 ixor   y41   x41   wkh ;
 iand   y01   x01   vfb ;
 iand   jgv   dkh   mph ;
 ior   gnp   jwb   bsb ;
 ior   cdk   fjh   gwm ;
 ior   prt   frs   kmg ;
 ixor   x17   y17   fpd ;
 iand   y42   x42   rtk ;
 iand   fpd   smg   tqm ;
 iand   dbv   vhs   gdw ;
 iand   y29   x29   wms ;
 ixor   kkh   bsb   z29 ;
 iand   cqp   dqm   trv ;
 iand   hvs   tsn   gmf ;
 iand   wkq   tfv   grv ;
 iand   x04   y04   ccq ;
 ixor   x20   y20   msw ;
 ixor   y26   x26   fgv ;
 ixor   mmr   qdc   z14 ;
 ixor   ghf   frn   z06 ;
 iand   y26   x26   wwt ;
 ior   sst   gdw   jgg ;
 ixor   pmn   wkh   z41 ;
 ixor   y04   x04   wkb ;
 ixor   y28   x28   chk ;
 ixor   wqr   qmr   z43 ;
 iand   kdv   stg   bcc ;
 iand   y18   x18   pvh ;
 ixor   mvk   tkc   z42 ;
 iand   x27   y27   cks ;
 ior   bjf   qkq   pmn ;
 iand   tkc   mvk   nrr ;
 ixor   y38   x38   gdk ;
 iand   y37   x37   jpk ;
 iand   x23   y23   twp ;
 ior   tqm   bmp   tsn ;
 ixor   wkb   drd   z04 ;
 ixor   x42   y42   mvk ;
 iand   y35   x35   pnj ;
 ixor   shm   tmd   z11 ;
 ixor   y24   x24   fnh ;
 iand   x11   y11   skj ;
 iand   x10   y10   fgc ;
 ior   srp   jcf   z05 ;
 iand   y12   x12   sqg ;
 ixor   y18   x18   hvs ;
foo());; 

let solution = bin2dec (foo ()) 0 1 ;;