;;;; terry.syms.import.scm - GENERATED BY CHICKEN 5.4.0rc2 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'terry.syms
      'terry.syms
      (scheme#list)
      '()
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
