;;;; terry.import.scm - GENERATED BY CHICKEN 5.4.0rc2 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (scheme#eval
      '(import-syntax bindings scheme chicken.syntax chicken.format))
    (import scheme)
    (import (chicken format))
    (import bindings)
    (##core#begin
      (define percent-symbol
        (lambda (s)
          (format #t "s => [~a]~%" s)
          (string->symbol (string-append "%" (symbol->string s)))))
      (define symbols->percents
        (lambda (xs)
          (map (lambda (x) `(,(percent-symbol x) (rename ',x))) xs))))
    (##sys#register-compiled-module
      'terry
      'terry
      (scheme#list)
      '()
      (scheme#list
        (scheme#cons
          'with-symbols
          (er-macro-transformer
            (lambda (exp rename compare?)
              (let* ((symbols (car (cdr exp)))
                     (body (cdr (cdr exp)))
                     (rename-list (symbols->percents symbols)))
                `(let ,rename-list ,@body)))))
        (scheme#cons
          'for-helper
          (er-macro-transformer
            (lambda (exp rename compare?)
              (let ((%loop (rename 'loop))
                    (%lambda (rename 'lambda))
                    (%when (rename 'when)))
                (bind (_ (var start stop cmp inc by) . body)
                      exp
                      `(letrec ((,%loop
                                 (,%lambda
                                  (,var)
                                  (,%when
                                   (,cmp ,var ,stop)
                                   ,@body
                                   (,%loop (,inc ,var ,by))))))
                         (,%loop ,start))))))))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
