;;;; with-symbols.import.scm - GENERATED BY CHICKEN 5.4.0rc2 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'with-symbols
      'with-symbols
      (scheme#list)
      '()
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
